var keywords_week = {
    "新纶科技": 887,
    "招商蛇口": 861,
    "浙江龙盛": 523,
    "上汽集团": 595,
    "华兰生物": 422,
    "光迅科技": 479,
    "银轮股份": 499,
    "开元股份": 424,
    "大秦铁路": 436,
    "苏宁易购": 357,
    "威创股份": 321,
    "分众传媒": 380,
    "智飞生物": 389,
    "中国化学": 351,
    "龙马环卫": 369,
    "楚江新材": 350,
    "东山精密": 392,
    "星宇股份": 400,
    "万华化学": 400,
    "视觉中国": 312,
    "道氏技术": 279,
    "中航沈飞": 242,
    "喜临门": 222,
    "长久物流": 280,
    "常熟汽饰": 244,
    "海信电器": 217,
    "广汇汽车": 293,
    "雷鸣科化": 264,
    "诺力股份": 288,
    "越博动力": 297,
    "复星医药": 279,
    "蒙娜丽莎": 287,
    "科斯伍德": 202,
    "高能环境": 236,
    "克来机电": 210,
    "华海药业": 228,
    "友宝在线": 209,
    "长江电力": 280,
    "科达股份": 225,
    "璞泰来": 289,
    "长亮科技": 236,
    "日机密封": 219,
    "金融街": 299,
    "光华科技": 272,
    "保利地产": 228,
    "华策影视": 294,
    "均胜电子": 263,
    "启迪桑德": 261,
    "三七互娱": 236,
    "平治信息": 268,
    "三特索道": 199,
    "老板电器": 190,
    "众生药业": 106,
    "京新药业": 135,
    "珠江啤酒": 119,
    "中颖电子": 130,
    "数据港": 195,
    "佩蒂股份": 165,
    "深信服": 142,
    "羚锐制药": 173,
    "康拓红外": 157,
    "亿帆医药": 107,
    "扬农化工": 189,
    "德展健康": 153,
    "道明光学": 119,
    "宝钢股份": 140,
    "东方航空": 147,
    "腾邦国际": 161,
    "科华生物": 146,
    "晶瑞股份": 111,
    "花嫁丽舍": 173,
    "艾瑞股份": 104,
    "阿尼股份": 144,
    "兆易创新": 166,
    "日发精机": 155,
    "工业富联": 192,
    "华东医药": 109,
    "华强方特": 112,
    "山东黄金": 120,
    "尚品宅配": 161,
    "润达医疗": 127,
    "泰豪科技": 192,
    "杰克股份": 145,
    "正泰电器": 135,
    "益生股份": 122,
    "东音股份": 118,
    "国创高新": 111,
    "顺鑫农业": 151,
    "神马股份": 189,
    "金龙汽车": 196,
    "阳煤化工": 138,
    "上实发展": 146,
    "中信银行": 131,
    "信捷电气": 106,
    "创业软件": 134,
    "重庆钢铁": 112,
    "当代明诚": 170,
    "比亚迪": 180,
    "科陆电子": 102,
    "申通快递": 175,
    "振芯科技": 170,
    "阳谷华泰": 131,
    "花园生物": 129,
    "南山铝业": 130,
    "荣泰健康": 151,
    "瀚蓝环境": 145,
    "科大讯飞": 127,
    "山东药玻": 122,
    "利群股份": 137,
    "海南瑞泽": 192,
    "东旭蓝天": 118,
    "四创电子": 159,
    "海普瑞": 194,
    "中金环境": 173,
    "鼎胜新材": 162,
    "豫园股份": 107,
    "大北农": 160,
    "广誉远": 116,
    "帝欧家居": 154,
    "九牧王": 125,
};
var keywords_month = {
    "银轮股份": 1710,
    "上汽集团": 1778,
    "中国国旅": 1510,
    "星宇股份": 1424,
    "智飞生物": 1359,
    "水井坊": 1242,
    "贵州茅台": 1248,
    "五粮液": 1165,
    "新纶科技": 988,
    "招商蛇口": 993,
    "生物股份": 978,
    "浙江鼎力": 936,
    "大秦铁路": 932,
    "顾家家居": 984,
    "苏宁易购": 867,
    "浙江龙盛": 887,
    "喜临门": 867,
    "中信证券": 804,
    "均胜电子": 870,
    "伊利股份": 827,
    "海澜之家": 860,
    "广汇汽车": 762,
    "复星医药": 702,
    "克来机电": 753,
    "华海药业": 724,
    "光迅科技": 754,
    "首旅酒店": 799,
    "森马服饰": 715,
    "三七互娱": 745,
    "锦江股份": 702,
    "北方华创": 755,
    "华友钴业": 741,
    "乐普医疗": 701,
    "山西汾酒": 711,
    "南方航空": 737,
    "盛通股份": 704,
    "荣泰健康": 632,
    "中国化学": 614,
    "招商银行": 670,
    "安科生物": 694,
    "开元股份": 664,
    "中国石化": 602,
    "浙江美大": 686,
    "太平鸟": 636,
    "徐工机械": 624,
    "跨境通": 630,
    "欧派家居": 644,
    "光线传媒": 616,
    "上海银行": 686,
    "重庆啤酒": 679,
    "内蒙一机": 679,
    "合力泰": 642,
    "中青旅": 607,
    "中国太保": 626,
    "好莱客": 626,
    "中牧股份": 688,
    "大参林": 691,
    "信捷电气": 517,
    "大北农": 587,
    "兖州煤业": 530,
    "云南白药": 581,
    "龙马环卫": 510,
    "东山精密": 557,
    "万华化学": 529,
    "宁波银行": 536,
    "莱克电气": 568,
    "慈文传媒": 566,
    "潍柴动力": 589,
    "中鼎股份": 518,
    "三安光电": 545,
    "普莱柯": 572,
    "美的集团": 519,
    "新华保险": 558,
    "中国长城": 535,
    "金龙汽车": 545,
    "新城控股": 500,
    "古井贡酒": 503,
    "用友网络": 558,
    "郑煤机": 540,
    "浪潮信息": 505,
    "格力电器": 547,
    "恒力股份": 592,
    "顺鑫农业": 550,
    "万孚生物": 588,
    "安图生物": 569,
    "韵达股份": 565,
    "中远海控": 518,
    "中际旭创": 593,
    "中集集团": 575,
    "天顺风能": 538,
    "亨通光电": 535,
    "宏发股份": 521,
    "一心堂": 597,
    "海天味业": 561,
    "上海医药": 522,
    "西王食品": 527,
    "潞安环能": 526,
    "申通快递": 476,
    "阳谷华泰": 468,
    "诺力股份": 424,
    "四创电子": 426,
    "中金环境": 404,
    "中炬高新": 426,
    "科斯伍德": 488,
    "高能环境": 420,
    "宇通客车": 482,
    "长江电力": 426,
    "新和成": 402,
    "保隆科技": 407,
    "国轩高科": 401,
    "恒瑞医药": 487,
    "应流股份": 459,
    "鄂武商A": 483,
    "中国平安": 456,
    "阳光电源": 483,
    "航天信息": 419,
    "京东方A": 483,
    "太阳纸业": 475,
    "视觉中国": 491,
    "亿联网络": 424,
};
var keywords_year = {
    "银轮股份": 3456,
    "三一重工": 3184,
    "智飞生物": 2909,
    "中顺洁柔": 2812,
    "启迪桑德": 2757,
    "三花智控": 2604,
    "绝味食品": 2657,
    "尚品宅配": 2678,
    "通化东宝": 2597,
    "恒立液压": 2461,
    "泸州老窖": 2451,
    "恒瑞医药": 2356,
    "碧水源": 2300,
    "爱尔眼科": 2376,
    "舍得酒业": 2100,
    "分众传媒": 2175,
    "北方华创": 2129,
    "东方园林": 2100,
    "晶盛机电": 2154,
    "杉杉股份": 2044,
    "欧派家居": 2029,
    "大族激光": 2043,
    "新纶科技": 1996,
    "开元股份": 1917,
    "保利地产": 1987,
    "浙江鼎力": 1917,
    "光线传媒": 1938,
    "精锻科技": 1953,
    "天顺风能": 1950,
    "上汽集团": 1838,
    "招商蛇口": 1811,
    "太平鸟": 1821,
    "美年健康": 1836,
    "拓普集团": 1813,
    "华宇软件": 1849,
    "国祯环保": 1859,
    "中炬高新": 1710,
    "喜临门": 1704,
    "视觉中国": 1707,
    "亿联网络": 1797,
    "泰格医药": 1799,
    "五粮液": 1793,
    "中牧股份": 1753,
    "家家悦": 1712,
    "佩蒂股份": 1701,
    "烽火通信": 1752,
    "云南白药": 1617,
    "浙江龙盛": 1609,
    "桃李面包": 1637,
    "飞科电器": 1645,
    "索菲亚": 1640,
    "中国国旅": 1621,
    "三七互娱": 1629,
    "顾家家居": 1626,
    "中际旭创": 1651,
    "华友钴业": 1613,
    "洽洽食品": 1667,
    "扬农化工": 1691,
    "片仔癀": 1644,
    "鲁西化工": 1676,
    "华策影视": 1562,
    "汇川技术": 1567,
    "海大集团": 1501,
    "南极电商": 1553,
    "双环传动": 1508,
    "汉得信息": 1563,
    "广汇汽车": 1439,
    "新安股份": 1417,
    "星宇股份": 1451,
    "阳光电源": 1449,
    "三安光电": 1400,
    "锦江股份": 1416,
    "上海银行": 1492,
    "歌力思": 1475,
    "重庆啤酒": 1495,
    "博世科": 1452,
    "恒顺醋业": 1459,
    "弘亚数控": 1496,
    "恩华药业": 1437,
    "正泰电器": 1432,
    "信捷电气": 1348,
    "克来机电": 1327,
    "光迅科技": 1308,
    "宇通客车": 1388,
    "林洋能源": 1349,
    "易华录": 1379,
    "昆仑万维": 1331,
    "京东方A": 1331,
    "荣盛发展": 1361,
    "伊利股份": 1351,
    "黄山旅游": 1312,
    "埃斯顿": 1378,
    "济川药业": 1336,
    "九州通": 1362,
    "安图生物": 1363,
    "宝钢股份": 1382,
    "华鲁恒升": 1366,
    "乐普医疗": 1368,
    "一心堂": 1332,
    "山西汾酒": 1349,
    "海天味业": 1325,
    "老板电器": 1339,
    "温氏股份": 1329,
    "宁波高发": 1336,
    "国瓷材料": 1344,
    "水井坊": 1273,
    "安科生物": 1274,
    "宝信软件": 1276,
    "华东医药": 1210,
    "长亮科技": 1295,
    "中国石化": 1229,
    "徐工机械": 1275,
    "国轩高科": 1257,
    "均胜电子": 1264,
    "大秦铁路": 1203,
    "中鼎股份": 1279,
    "太阳纸业": 1270,
    "隆基股份": 1216,
    "森马服饰": 1286,
    "顺网科技": 1211,
};


var data_week = [];
var data_month = [];
var data_year = [];

for (var name in keywords_week) {
    data_week.push({
        name: name,
        value: Math.sqrt(keywords_week[name])
    })
}
for (var name in keywords_month) {
    data_month.push({
        name: name,
        value: Math.sqrt(keywords_month[name])
    })
}
for (var name in keywords_year) {
    data_year.push({
        name: name,
        value: Math.sqrt(keywords_year[name])
    })
}
// data = data.sort(function(a, b) {
//     return b.value - a.value;
// })
// console.log(data);
var option_week = {
    tooltip: {},
    series: [{
        type: 'wordCloud',
        gridSize: 13,
        sizeRange: [15, 70],
        rotationRange: [-90, 90],
        shape: 'cloud',
        width: 1500,
        height: 1080,
        drawOutOfBound: true,
        textStyle: {
            normal: {
                color: function() {
                    return 'rgb(' + [
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160)
                    ].join(',') + ')';
                }
            },
            emphasis: {
                shadowBlur: 10,
                shadowColor: '#333'
            }
        },
        data: data_week
    }]
};
var option_month = {
    tooltip: {},
    series: [{
        type: 'wordCloud',
        gridSize: 13,
        sizeRange: [13, 70],
        rotationRange: [-90, 90],
        shape: 'cloud',
        width: 1500,
        height: 1080,
        drawOutOfBound: true,
        textStyle: {
            normal: {
                color: function() {
                    return 'rgb(' + [
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160)
                    ].join(',') + ')';
                }
            },
            emphasis: {
                shadowBlur: 10,
                shadowColor: '#333'
            }
        },
        data: data_month
    }]
};
var option_year = {
    tooltip: {},
    series: [{
        type: 'wordCloud',
        gridSize: 10,
        sizeRange: [13, 73],
        rotationRange: [-90, 90],
        shape: 'cloud',
        width: 1500,
        height: 1080,
        drawOutOfBound: true,
        textStyle: {
            normal: {
                color: function() {
                    return 'rgb(' + [
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160)
                    ].join(',') + ')';
                }
            },
            emphasis: {
                shadowBlur: 10,
                shadowColor: '#333'
            }
        },
        data: data_year
    }]
};


$(function() {
    var chart = echarts.init(document.getElementById('main1'));
    $("#loading").removeClass("hidden");
    $("#week").click(function() {
        $("#wordCloud button").removeClass("btn-primary");
        $("#week").addClass("btn-primary");
        setTimeout(function() {
            $("#loading").addClass("hidden");
            chart.setOption(option_week);
        }, 100);
        // $('#table').bootstrapTable('removeAll');
        // $('#table').bootstrapTable('refresh', {url: './data/data_week.json'});

    });
    $("#month").click(function() {
        $("#wordCloud button").removeClass("btn-primary");
        $("#month").addClass("btn-primary");
        setTimeout(function() {
            $("#loading").addClass("hidden");
            chart.setOption(option_month);
        }, 100);
        $('#table').bootstrapTable({
            search: true,
            cardView: false,
            showToggle: true,
            showColumns: true,
            columns: [{
                field: 'stock',
                title: '股票名称',
                align: "center"
            }, {
                field: 'ratio',
                title: '频率',
                align: "center"
            }],
            data: [{ "stock": '银轮股份', "ratio": 1739 },
                { "stock": '上汽集团', "ratio": 1732 },
                { "stock": '中国国旅', "ratio": 1530 },
                { "stock": '星宇股份', "ratio": 1422 },
                { "stock": '智飞生物', "ratio": 1341 },
                { "stock": '水井坊', "ratio": 1271 },
                { "stock": '贵州茅台', "ratio": 1229 },
                { "stock": '五粮液', "ratio": 1125 },
                { "stock": '新纶科技', "ratio": 975 },
                { "stock": '招商蛇口', "ratio": 988 },
                { "stock": '生物股份', "ratio": 989 },
                { "stock": '浙江鼎力', "ratio": 973 },
                { "stock": '大秦铁路', "ratio": 918 },
                { "stock": '顾家家居', "ratio": 985 },
                { "stock": '苏宁易购', "ratio": 864 },
                { "stock": '浙江龙盛', "ratio": 868 },
                { "stock": '喜临门', "ratio": 859 },
                { "stock": '中信证券', "ratio": 844 },
                { "stock": '均胜电子', "ratio": 848 },
                { "stock": '伊利股份', "ratio": 879 },
                { "stock": '海澜之家', "ratio": 872 },
                { "stock": '广汇汽车', "ratio": 751 },
                { "stock": '复星医药', "ratio": 739 },
                { "stock": '克来机电', "ratio": 719 },
                { "stock": '华海药业', "ratio": 703 },
                { "stock": '光迅科技', "ratio": 766 },
                { "stock": '首旅酒店', "ratio": 771 },
                { "stock": '森马服饰', "ratio": 726 },
                { "stock": '三七互娱', "ratio": 732 },
                { "stock": '锦江股份', "ratio": 763 },
                { "stock": '北方华创', "ratio": 763 },
                { "stock": '华友钴业', "ratio": 719 },
                { "stock": '乐普医疗', "ratio": 732 },
                { "stock": '山西汾酒', "ratio": 715 },
                { "stock": '南方航空', "ratio": 752 },
                { "stock": '盛通股份', "ratio": 718 },
                { "stock": '荣泰健康', "ratio": 660 },
                { "stock": '中国化学', "ratio": 660 },
                { "stock": '招商银行', "ratio": 658 },
                { "stock": '安科生物', "ratio": 683 },
                { "stock": '开元股份', "ratio": 643 },
                { "stock": '中国石化', "ratio": 600 },
                { "stock": '浙江美大', "ratio": 636 },
                { "stock": '太平鸟', "ratio": 613 },
                { "stock": '徐工机械', "ratio": 675 },
                { "stock": '跨境通', "ratio": 621 },
                { "stock": '欧派家居', "ratio": 687 },
                { "stock": '光线传媒', "ratio": 637 },
                { "stock": '上海银行', "ratio": 642 },
                { "stock": '重庆啤酒', "ratio": 638 },
                { "stock": '内蒙一机', "ratio": 609 },
                { "stock": '合力泰', "ratio": 625 },
                { "stock": '中青旅', "ratio": 663 },
                { "stock": '中国太保', "ratio": 652 },
                { "stock": '好莱客', "ratio": 689 },
                { "stock": '中牧股份', "ratio": 665 },
                { "stock": '大参林', "ratio": 692 },
                { "stock": '信捷电气', "ratio": 589 },
                { "stock": '大北农', "ratio": 546 },
                { "stock": '兖州煤业', "ratio": 514 },
                { "stock": '云南白药', "ratio": 530 },
                { "stock": '龙马环卫', "ratio": 502 },
                { "stock": '东山精密', "ratio": 539 },
                { "stock": '万华化学', "ratio": 583 },
                { "stock": '宁波银行', "ratio": 513 },
                { "stock": '莱克电气', "ratio": 589 },
                { "stock": '慈文传媒', "ratio": 515 },
                { "stock": '潍柴动力', "ratio": 503 },
                { "stock": '中鼎股份', "ratio": 508 },
                { "stock": '三安光电', "ratio": 514 },
                { "stock": '普莱柯', "ratio": 506 },
                { "stock": '美的集团', "ratio": 589 },
                { "stock": '新华保险', "ratio": 530 },
                { "stock": '中国长城', "ratio": 574 },
                { "stock": '金龙汽车', "ratio": 595 },
                { "stock": '新城控股', "ratio": 571 },
                { "stock": '古井贡酒', "ratio": 537 },
                { "stock": '用友网络', "ratio": 551 },
                { "stock": '郑煤机', "ratio": 553 },
                { "stock": '浪潮信息', "ratio": 547 },
                { "stock": '格力电器', "ratio": 600 },
                { "stock": '恒力股份', "ratio": 509 },
                { "stock": '顺鑫农业', "ratio": 538 },
                { "stock": '万孚生物', "ratio": 577 },
                { "stock": '安图生物', "ratio": 516 },
                { "stock": '韵达股份', "ratio": 526 },
                { "stock": '中远海控', "ratio": 508 },
                { "stock": '中际旭创', "ratio": 554 },
                { "stock": '中集集团', "ratio": 535 },
                { "stock": '天顺风能', "ratio": 582 },
                { "stock": '亨通光电', "ratio": 512 },
                { "stock": '宏发股份', "ratio": 528 },
                { "stock": '一心堂', "ratio": 541 },
                { "stock": '海天味业', "ratio": 596 },
                { "stock": '上海医药', "ratio": 589 },
                { "stock": '西王食品', "ratio": 536 },
                { "stock": '潞安环能', "ratio": 563 },
                { "stock": '申通快递', "ratio": 419 },
                { "stock": '阳谷华泰', "ratio": 439 },
                { "stock": '诺力股份', "ratio": 410 },
                { "stock": '四创电子', "ratio": 458 },
                { "stock": '中金环境', "ratio": 427 },
                { "stock": '中炬高新', "ratio": 498 },
                { "stock": '科斯伍德', "ratio": 458 },
                { "stock": '高能环境', "ratio": 463 },
                { "stock": '宇通客车', "ratio": 447 },
                { "stock": '长江电力', "ratio": 494 },
                { "stock": '新和成', "ratio": 480 },
                { "stock": '保隆科技', "ratio": 401 },
                { "stock": '国轩高科', "ratio": 470 },
                { "stock": '恒瑞医药', "ratio": 438 },
                { "stock": '应流股份', "ratio": 500 },
                { "stock": '鄂武商A', "ratio": 420 },
                { "stock": '中国平安', "ratio": 456 },
                { "stock": '阳光电源', "ratio": 473 },
                { "stock": '航天信息', "ratio": 400 },
                { "stock": '京东方A', "ratio": 477 },
                { "stock": '太阳纸业', "ratio": 411 },
                { "stock": '视觉中国', "ratio": 482 },
                { "stock": '亿联网络', "ratio": 476 }
            ]
        });
    });
    $("#year").click(function() {
        $("#wordCloud button").removeClass("btn-primary");
        $("#year").addClass("btn-primary");
        setTimeout(function() {
            $("#loading").addClass("hidden");
            chart.setOption(option_year);
        }, 100);
        $('#table').bootstrapTable({
            search: true,
            cardView: false,
            showToggle: true,
            showColumns: true,
            columns: [{
                field: 'stock',
                title: '股票名称',
                align: "center"
            }, {
                field: 'ratio',
                title: '频率',
                align: "center"
            }],
            data: [{ "stock": '银轮股份', "ratio": 3441 },
                { "stock": '三一重工', "ratio": 3196 },
                { "stock": '智飞生物', "ratio": 2910 },
                { "stock": '中顺洁柔', "ratio": 2841 },
                { "stock": '启迪桑德', "ratio": 2724 },
                { "stock": '三花智控', "ratio": 2632 },
                { "stock": '绝味食品', "ratio": 2637 },
                { "stock": '尚品宅配', "ratio": 2653 },
                { "stock": '通化东宝', "ratio": 2544 },
                { "stock": '恒立液压', "ratio": 2493 },
                { "stock": '泸州老窖', "ratio": 2481 },
                { "stock": '恒瑞医药', "ratio": 2361 },
                { "stock": '碧水源', "ratio": 2371 },
                { "stock": '爱尔眼科', "ratio": 2375 },
                { "stock": '舍得酒业', "ratio": 2157 },
                { "stock": '分众传媒', "ratio": 2183 },
                { "stock": '北方华创', "ratio": 2110 },
                { "stock": '东方园林', "ratio": 2197 },
                { "stock": '晶盛机电', "ratio": 2185 },
                { "stock": '杉杉股份', "ratio": 2059 },
                { "stock": '欧派家居', "ratio": 2052 },
                { "stock": '大族激光', "ratio": 2067 },
                { "stock": '新纶科技', "ratio": 1945 },
                { "stock": '开元股份', "ratio": 1994 },
                { "stock": '保利地产', "ratio": 1960 },
                { "stock": '浙江鼎力', "ratio": 1949 },
                { "stock": '光线传媒', "ratio": 1938 },
                { "stock": '精锻科技', "ratio": 2000 },
                { "stock": '天顺风能', "ratio": 1933 },
                { "stock": '上汽集团', "ratio": 1898 },
                { "stock": '招商蛇口', "ratio": 1897 },
                { "stock": '太平鸟', "ratio": 1833 },
                { "stock": '美年健康', "ratio": 1839 },
                { "stock": '拓普集团', "ratio": 1867 },
                { "stock": '华宇软件', "ratio": 1879 },
                { "stock": '国祯环保', "ratio": 1835 },
                { "stock": '中炬高新', "ratio": 1744 },
                { "stock": '喜临门', "ratio": 1729 },
                { "stock": '视觉中国', "ratio": 1739 },
                { "stock": '亿联网络', "ratio": 1779 },
                { "stock": '泰格医药', "ratio": 1709 },
                { "stock": '五粮液', "ratio": 1768 },
                { "stock": '中牧股份', "ratio": 1759 },
                { "stock": '家家悦', "ratio": 1741 },
                { "stock": '佩蒂股份', "ratio": 1765 },
                { "stock": '烽火通信', "ratio": 1737 },
                { "stock": '云南白药', "ratio": 1648 },
                { "stock": '浙江龙盛', "ratio": 1684 },
                { "stock": '桃李面包', "ratio": 1611 },
                { "stock": '飞科电器', "ratio": 1682 },
                { "stock": '索菲亚', "ratio": 1621 },
                { "stock": '中国国旅', "ratio": 1633 },
                { "stock": '三七互娱', "ratio": 1673 },
                { "stock": '顾家家居', "ratio": 1679 },
                { "stock": '中际旭创', "ratio": 1665 },
                { "stock": '华友钴业', "ratio": 1632 },
                { "stock": '洽洽食品', "ratio": 1679 },
                { "stock": '扬农化工', "ratio": 1675 },
                { "stock": '片仔癀', "ratio": 1693 },
                { "stock": '鲁西化工', "ratio": 1624 },
                { "stock": '华策影视', "ratio": 1548 },
                { "stock": '汇川技术', "ratio": 1546 },
                { "stock": '海大集团', "ratio": 1525 },
                { "stock": '南极电商', "ratio": 1566 },
                { "stock": '双环传动', "ratio": 1505 },
                { "stock": '汉得信息', "ratio": 1564 },
                { "stock": '广汇汽车', "ratio": 1401 },
                { "stock": '新安股份', "ratio": 1403 },
                { "stock": '星宇股份', "ratio": 1435 },
                { "stock": '阳光电源', "ratio": 1403 },
                { "stock": '三安光电', "ratio": 1405 },
                { "stock": '锦江股份', "ratio": 1500 },
                { "stock": '上海银行', "ratio": 1440 },
                { "stock": '歌力思', "ratio": 1413 },
                { "stock": '重庆啤酒', "ratio": 1403 },
                { "stock": '博世科', "ratio": 1403 },
                { "stock": '恒顺醋业', "ratio": 1408 },
                { "stock": '弘亚数控', "ratio": 1441 },
                { "stock": '恩华药业', "ratio": 1489 },
                { "stock": '正泰电器', "ratio": 1419 },
                { "stock": '信捷电气', "ratio": 1343 },
                { "stock": '克来机电', "ratio": 1315 },
                { "stock": '光迅科技', "ratio": 1372 },
                { "stock": '宇通客车', "ratio": 1375 },
                { "stock": '林洋能源', "ratio": 1340 },
                { "stock": '易华录', "ratio": 1371 },
                { "stock": '昆仑万维', "ratio": 1356 },
                { "stock": '京东方A', "ratio": 1392 },
                { "stock": '荣盛发展', "ratio": 1325 },
                { "stock": '伊利股份', "ratio": 1358 },
                { "stock": '黄山旅游', "ratio": 1385 },
                { "stock": '埃斯顿', "ratio": 1390 },
                { "stock": '济川药业', "ratio": 1382 },
                { "stock": '九州通', "ratio": 1326 },
                { "stock": '安图生物', "ratio": 1393 },
                { "stock": '宝钢股份', "ratio": 1327 },
                { "stock": '华鲁恒升', "ratio": 1325 },
                { "stock": '乐普医疗', "ratio": 1384 },
                { "stock": '一心堂', "ratio": 1387 },
                { "stock": '山西汾酒', "ratio": 1377 },
                { "stock": '海天味业', "ratio": 1352 },
                { "stock": '老板电器', "ratio": 1384 },
                { "stock": '温氏股份', "ratio": 1378 },
                { "stock": '宁波高发', "ratio": 1389 },
                { "stock": '国瓷材料', "ratio": 1349 },
                { "stock": '水井坊', "ratio": 1216 },
                { "stock": '安科生物', "ratio": 1245 },
                { "stock": '宝信软件', "ratio": 1201 },
                { "stock": '华东医药', "ratio": 1299 },
                { "stock": '长亮科技', "ratio": 1226 },
                { "stock": '中国石化', "ratio": 1254 },
                { "stock": '徐工机械', "ratio": 1208 },
                { "stock": '国轩高科', "ratio": 1212 },
                { "stock": '均胜电子', "ratio": 1202 },
                { "stock": '大秦铁路', "ratio": 1221 },
                { "stock": '中鼎股份', "ratio": 1225 },
                { "stock": '太阳纸业', "ratio": 1235 },
                { "stock": '隆基股份', "ratio": 1203 },
                { "stock": '森马服饰', "ratio": 1237 },
                { "stock": '顺网科技', "ratio": 1230 },
            ]
        });
    });

    $("#month").click();
    // 个人中心
    $(".tulipDialog-model,#login-wrap").first().addClass("hidden");
    $("#menu").css("margin-right", "42px");
    $("#userCenter").removeClass("hidden");


})